FROM python:3.8

RUN pip install numpy

# Install MountainSort4
RUN pip install mountainsort4==1.0.0

RUN pip install simplejson requests click

# spikeinterface/spikesorters
RUN pip install spikesorters==0.4.4

LABEL version="1.0.0"